# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DatabaseSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DatabaseSample
  #pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'DatabaseSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DatabaseSample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DatabaseSample-tvOS

  target 'DatabaseSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
